import { Button, VerticalBox, LineEdit, CheckBox,Spinner } from "std-widgets.slint";

export component AppWindow inherits Window {
    background: #313e50;
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
           Text {
                text: "Login Window";
                font-size: 24px;
                horizontal-alignment: center;
                font-weight: 1000;                
           }
        }
        Row {
            LineEdit { // Username
                horizontal-alignment: left;
                font-size: 16px;
                placeholder-text: "Username";
                height: 35px;
            }
        }
        Row {
            LineEdit { // Password
                horizontal-alignment: left;
                font-size: 16px;
                placeholder-text: "Password";
                input-type: password;
                height: 35px;
            }
        }
        CheckBox {
            height: 35px;
            horizontal-stretch: 1;
            text: "Save Password?";
        }    
        Row{
            Button {
                text: "Login in";
                primary: true;
                height: 35px;

        }
    }
}
    }
